-- Extended seed data with 20 more profiles including kinks and lifestyle details
-- Delete existing users and start fresh with 30 total profiles

DELETE FROM users;

-- Insert 30 users with complete profiles, kinks, and lifestyle details
INSERT INTO users (phone, email, name, gender, looking_for, bio, birthdate, photos, tags, kinks, height, body_type, drinking, smoking, relationship_type, credits, is_verified) VALUES
-- Original 10 users (updated with kinks)
('9876543210', 'priya.sharma@email.com', 'Priya Sharma', 'female', 'male', 'Coffee addict ☕ | Travel enthusiast 🌍 | Here for a good time, not a long time 😈', '1995-03-15', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8DwHwAFBQIAX8jx0gAAAABJRU5ErkJggg=='], ARRAY['coffee', 'travel', 'books'], ARRAY['Dominant', 'Role Play', 'Sensual Massage'], '5''4"', 'Slim', 'Socially', 'Never', 'Casual', 100, true),
('9876543211', 'rahul.verma@email.com', 'Rahul Verma', 'male', 'female', 'Fitness freak 💪 | Looking for my workout partner... in bed 😏', '1993-07-20', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/A8B8ABQICfxjx0gAAAABJRU5ErkJggg=='], ARRAY['fitness', 'tech', 'food'], ARRAY['Submissive', 'Toys', 'Outdoor'], '5''11"', 'Athletic', 'Regularly', 'Never', 'FWB', 150, true),
('9876543212', 'ananya.singh@email.com', 'Ananya Singh', 'female', 'male', 'Artist by day, wild child by night 🌙 No strings attached vibes only', '1996-11-08', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkaGj4HwADBgI/hPlnmQAAAABJRU5ErkJggg=='], ARRAY['art', 'dogs', 'adventure'], ARRAY['Bondage Light', 'Exhibition', 'Spontaneous'], '5''6"', 'Curvy', 'Socially', 'Sometimes', 'ONS', 80, true),
('9876543213', 'arjun.patel@email.com', 'Arjun Patel', 'male', 'female', 'Entrepreneur | My safe word is "Investments" 💼😈', '1992-05-12', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPj/HwADBgI/hOtJHAAAAABJRU5ErkJggg=='], ARRAY['music', 'bikes', 'business'], ARRAY['Dominant', 'Power Play', 'Dirty Talk'], '6''0"', 'Fit', 'Regularly', 'Never', 'Casual', 200, true),
('9876543214', 'sneha.reddy@email.com', 'Sneha Reddy', 'female', 'male', 'Yoga instructor 🧘 | Very flexible... in every way 😉', '1997-09-25', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP4z8DwHwAFAAH/VscvDQAAAABJRU5ErkJggg=='], ARRAY['yoga', 'nature', 'wellness'], ARRAY['Tantric', 'Sensual', 'Massage'], '5''5"', 'Toned', 'Rarely', 'Never', 'FWB', 120, true),
('9876543215', 'vikram.kumar@email.com', 'Vikram Kumar', 'male', 'female', 'Software engineer 👨‍💻 | I know how to push all the right buttons 🎮', '1994-01-30', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+P//PwAGBAL/VeLrawAAAABJRU5ErkJggg=='], ARRAY['coding', 'gaming', 'anime'], ARRAY['Switch', 'Cosplay', 'Role Play'], '5''9"', 'Average', 'Socially', 'Never', 'Casual', 90, true),
('9876543216', 'ishita.joshi@email.com', 'Ishita Joshi', 'female', 'male', 'Fashion blogger 👗 | I look even better without clothes 😏', '1995-06-18', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+B4T8ABQYC/0Y8tDEAAAAASUVORK5CYII='], ARRAY['fashion', 'wine', 'beach'], ARRAY['Exhibition', 'Lingerie', 'Photography'], '5''7"', 'Slim', 'Regularly', 'Socially', 'ONS', 110, true),
('9876543217', 'rohan.mehta@email.com', 'Rohan Mehta', 'male', 'female', 'Photographer 📸 | Expert at capturing your best angles... and positions', '1991-12-05', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+A+EDAAABgAB/VhLkAAAAABJRU5ErkJggg=='], ARRAY['photography', 'travel', 'beer'], ARRAY['Voyeur', 'Photography', 'Outdoor'], '5''10"', 'Athletic', 'Regularly', 'Never', 'FWB', 180, true),
('9876543218', 'kavya.nair@email.com', 'Kavya Nair', 'female', 'male', 'Dentist 🦷 | I promise to be gentle... unless you dont want me to 😈', '1996-04-22', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+P+fAQAEAwH/sI2qNAAAAABJRU5ErkJggg=='], ARRAY['dance', 'food', 'desserts'], ARRAY['Switch', 'Biting', 'Rough'], '5''3"', 'Petite', 'Socially', 'Never', 'Casual', 95, true),
('9876543219', 'aditya.chopra@email.com', 'Aditya Chopra', 'male', 'female', 'Investment banker 💼 | High risk, high reward... same applies to my bedroom 🔥', '1990-08-14', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z/C/HgAGggJ/QMNMiAAAAABJRU5ErkJggg=='], ARRAY['finance', 'running', 'whiskey'], ARRAY['Dominant', 'Rough', 'Choking Light'], '6''1"', 'Fit', 'Regularly', 'Cigars', 'FWB', 250, true),

-- 20 NEW PROFILES
('9876543220', 'meera.krishnan@email.com', 'Meera Krishnan', 'female', 'male', 'Classical dancer turned club queen 💃 Flexible in more ways than one', '1998-02-14', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wnwEABQICf4hVxDsAAAAASUVORK5CYII='], ARRAY['dance', 'clubbing', 'music'], ARRAY['Submissive', 'Blindfolds', 'Sensory Play'], '5''4"', 'Slim', 'Regularly', 'Never', 'ONS', 85, true),
('9876543221', 'karan.malhotra@email.com', 'Karan Malhotra', 'male', 'female', 'Gym trainer by day, bedroom athlete by night 🏋️ Stamina for days', '1991-06-22', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkaGD4DwADBQH/dLw9AAAAASUVORK5CYII='], ARRAY['gym', 'protein', 'cardio'], ARRAY['Dominant', 'Rough', 'Marathon'], '6''2"', 'Muscular', 'Rarely', 'Never', 'Casual', 175, true),
('9876543222', 'simran.kaur@email.com', 'Simran Kaur', 'female', 'male', 'Air hostess ✈️ Mile high club member seeking new recruits', '1995-09-10', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z/C/AQAGAwH/GsNRowAAAABJRU5ErkJggg=='], ARRAY['travel', 'luxury', 'adventure'], ARRAY['Exhibition', 'Public', 'Spontaneous'], '5''8"', 'Slim', 'Socially', 'Never', 'FWB', 140, true),
('9876543223', 'dev.sharma@email.com', 'Dev Sharma', 'male', 'female', 'Bartender 🍸 I know how to shake things up and keep you thirsty', '1993-12-03', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYGD8DwABBAEAfTYW2AAAAABJRU5ErkJggg=='], ARRAY['cocktails', 'nightlife', 'music'], ARRAY['Switch', 'Ice Play', 'Food Play'], '5''11"', 'Lean', 'Regularly', 'Socially', 'ONS', 130, true),
('9876543224', 'pooja.agarwal@email.com', 'Pooja Agarwal', 'female', 'male', 'Startup founder 💻 I give great... pitch decks. And other things 😈', '1994-04-28', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/I8B8ABQYC/+VY+OsAAAAASUVORK5CYII='], ARRAY['startup', 'hustle', 'wine'], ARRAY['Dominant', 'Power Play', 'Degradation Light'], '5''5"', 'Fit', 'Regularly', 'Never', 'Casual', 200, true),
('9876543225', 'nikhil.gupta@email.com', 'Nikhil Gupta', 'male', 'female', 'Doctor 🩺 I have great hands and know anatomy very well', '1989-07-15', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+P+PAQAFmQL/xPxYwAAAAABJRU5ErkJggg=='], ARRAY['medicine', 'golf', 'wine'], ARRAY['Sensual', 'Massage', 'Slow Burn'], '5''10"', 'Average', 'Socially', 'Never', 'FWB', 220, true),
('9876543226', 'rhea.kapoor@email.com', 'Rhea Kapoor', 'female', 'male', 'Model 📸 These curves dont come with a warning label', '1997-11-20', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z/C/EQAGBAL/Il6q6wAAAABJRU5ErkJggg=='], ARRAY['modeling', 'fashion', 'luxury'], ARRAY['Exhibition', 'Lingerie', 'Photography'], '5''9"', 'Slim', 'Socially', 'Socially', 'Casual', 160, true),
('9876543227', 'amit.saxena@email.com', 'Amit Saxena', 'male', 'female', 'Chef 👨‍🍳 I can make you breakfast after making you scream', '1992-03-08', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkaGj8DwADBgL/4bT5oAAAAABJRU5ErkJggg=='], ARRAY['cooking', 'food', 'wine'], ARRAY['Sensual', 'Food Play', 'Kitchen Fun'], '5''8"', 'Stocky', 'Regularly', 'Never', 'FWB', 145, true),
('9876543228', 'tanya.bhatia@email.com', 'Tanya Bhatia', 'female', 'male', 'Lawyer ⚖️ I object to wearing clothes in bed', '1993-08-17', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8////fwYAAwAB/gn+GkEAAAAASUVORK5CYII='], ARRAY['law', 'debate', 'power'], ARRAY['Dominant', 'Role Play', 'Verbal'], '5''6"', 'Fit', 'Regularly', 'Never', 'Casual', 190, true),
('9876543229', 'rajat.singhania@email.com', 'Rajat Singhania', 'male', 'female', 'Pilot ✈️ Expert at take-offs and landings... if you know what I mean', '1990-01-25', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wvx4AB3YC/yEebD8AAAAASUVORK5CYII='], ARRAY['aviation', 'travel', 'adventure'], ARRAY['Dominant', 'Mile High', 'Spontaneous'], '6''0"', 'Athletic', 'Socially', 'Never', 'FWB', 230, true),
('9876543230', 'divya.menon@email.com', 'Divya Menon', 'female', 'male', 'Psychologist 🧠 I know exactly what youre thinking... and wanting', '1994-12-12', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z/DfGAAHCAL/kYIZSQAAAABJRU5ErkJggg=='], ARRAY['psychology', 'books', 'mind'], ARRAY['Mind Games', 'Teasing', 'Edging'], '5''4"', 'Average', 'Rarely', 'Never', 'Casual', 115, true),
('9876543231', 'varun.dhawan@email.com', 'Varun Dhawan', 'male', 'female', 'DJ 🎧 I know how to make you move... all night long', '1995-05-05', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/I8B8ABwYC/9eKk+sAAAAASUVORK5CYII='], ARRAY['music', 'EDM', 'parties'], ARRAY['Rhythm', 'Stamina', 'All Night'], '5''11"', 'Lean', 'Regularly', 'Socially', 'ONS', 135, true),
('9876543232', 'aisha.khan@email.com', 'Aisha Khan', 'female', 'male', 'Interior designer 🏠 Expert at making things look AND feel good', '1996-07-30', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z/CfEQAHBwL/TlFJ2gAAAABJRU5ErkJggg=='], ARRAY['design', 'aesthetics', 'home'], ARRAY['Sensual', 'Ambiance', 'Slow Burn'], '5''5"', 'Curvy', 'Socially', 'Never', 'FWB', 125, true),
('9876543233', 'siddharth.roy@email.com', 'Siddharth Roy', 'male', 'female', 'Filmmaker 🎬 I direct... especially in the bedroom', '1991-09-18', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkaGj4HwAEBQL/lEbcZAAAAABJRU5ErkJggg=='], ARRAY['cinema', 'art', 'stories'], ARRAY['Voyeur', 'Director', 'Role Play'], '5''10"', 'Average', 'Regularly', 'Socially', 'Casual', 170, true),
('9876543234', 'naina.sharma@email.com', 'Naina Sharma', 'female', 'male', 'Nurse 👩‍⚕️ I can take care of you... or be very naughty 😏', '1997-02-28', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+B8T8AB/4C/wQNAWoAAAAASUVORK5CYII='], ARRAY['healthcare', 'caring', 'fitness'], ARRAY['Role Play', 'Uniform', 'Caring'], '5''3"', 'Petite', 'Socially', 'Never', 'FWB', 105, true),
('9876543235', 'akash.mehta@email.com', 'Akash Mehta', 'male', 'female', 'Tattoo artist 🎨 I love leaving my mark on you', '1993-04-12', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+P/fEAAF7gL/xPz4JAAAAABJRU5ErkJggg=='], ARRAY['tattoos', 'art', 'alternative'], ARRAY['Pain Play Light', 'Marking', 'Artistic'], '5''9"', 'Lean', 'Socially', 'Regularly', 'ONS', 140, true),
('9876543236', 'kiara.advani@email.com', 'Kiara Advani', 'female', 'male', 'Actress 🎭 Great at playing different roles... especially for you', '1995-10-08', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z/C/CQAH9wL/F/U6gAAAAABJRU5ErkJggg=='], ARRAY['acting', 'drama', 'fame'], ARRAY['Role Play', 'Fantasy', 'Performance'], '5''6"', 'Slim', 'Socially', 'Never', 'Casual', 185, true),
('9876543237', 'rishi.kapoor@email.com', 'Rishi Kapoor', 'male', 'female', 'Personal trainer 💪 Ill make you sweat in AND out of the gym', '1992-11-30', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPjPCAAFzAL/xN1G4QAAAABJRU5ErkJggg=='], ARRAY['fitness', 'health', 'strength'], ARRAY['Dominant', 'Stamina', 'Strength Play'], '6''1"', 'Muscular', 'Rarely', 'Never', 'FWB', 165, true),
('9876543238', 'anushka.desai@email.com', 'Anushka Desai', 'female', 'male', 'Event planner 🎉 I throw great parties... and myself at hot guys', '1996-06-15', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8////PwYABP4C/8gZnHMAAAAASUVORK5CYII='], ARRAY['events', 'parties', 'social'], ARRAY['Spontaneous', 'Public', 'Thrill'], '5''7"', 'Athletic', 'Regularly', 'Socially', 'ONS', 155, true),
('9876543239', 'kabir.bedi@email.com', 'Kabir Bedi', 'male', 'female', 'Musician 🎸 My fingers are talented... on and off the guitar', '1994-08-22', ARRAY['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+P+/HgAG9gL/4ZfcEgAAAABJRU5ErkJggg=='], ARRAY['music', 'guitar', 'rock'], ARRAY['Sensual', 'Finger Work', 'Rhythm'], '5''10"', 'Lean', 'Regularly', 'Socially', 'Casual', 145, true);

-- Verify count
SELECT COUNT(*) as total_users FROM users;
